apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myweb-deployment
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: tristala/flask-app:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 5000