apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  selector:
   app: myweb
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000